#!/bin/sh

. /etc/profile

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

#
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s
# coldplug modules
find /sys/ -name modalias -print0 | xargs -0 sort -u | tr '\n' '\0' | xargs -0 modprobe -abq

#
echo "[rcS] loading modules..."
modprobe tntfs
modprobe h9_1
modprobe h9_2
modprobe h9_3
modprobe h9_4

echo "starting interface"
/etc/init.d/mountall start

echo "mounting everything"
/etc/init.d/mount_everything

modprobe mali

wifi=`lsusb | grep -c 0bda:818b`
if [ $wifi  == 1 ]; then
  	modprobe cfg80211
  	modprobe 8192eu
fi

echo "[rcS] add mmcblks in /dev/block"
/etc/init.d/mmcblk-by-name

echo "[rcS] mount zukonMOD Zgemma H9 multiboot if exists"
if [ -e /media/zukonMOD_system ]; then
  mount /media/zukonMOD_system /boot
fi

echo "setup network"
/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
NFS=$(grep -c nfs /proc/cmdline)
  if [ "$NFS" -eq "1" ]; then
    echo "Booting from nfs, don't set network"
    elif [ -e /var/tuxbox/config/.bootargs ]; then
    echo "using ip set via bootargs, don't reset network"
  else
    if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=$(grep -c dhcp /etc/network/interfaces)
      if [ "$DHCP" -eq "1" ]; then
        echo "Starting dhcp"
        /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
    fi
  fi
/sbin/ifconfig lo 127.0.0.1 up

# set dummy time
date -s "2017-01-01 00:00"

# rcS.local
if [ -e /etc/init.d/rcS.local ]; then 
	/etc/init.d/rcS.local
fi

# rcS.gui
if [ -e /etc/init.d/rcS.gui ]; then
	/etc/init.d/rcS.gui
fi

