# null may already exist; therefore ownership has to be changed with command
null		root:root 0666 @chmod 666 $MDEV
zero		root:root 0666
full		root:root 0666
random		root:root 0444
urandom		root:root 0444
hwrandom	root:root 0444
grsec		root:root 0660
initctl		root:root 0600

kmem		root:root 0640
mem		root:root 0640
port		root:root 0640
# console may already exist; therefore ownership has to be changed with command
console		root:root 0600 @chmod 600 $MDEV
ptmx		root:root 0666
pty.*		root:root 0660

# keep defaults
#.*       	root:root 0660

# lirc
lirc([0-9])	root:video	0660	>lirc/%1

# dri
dri/.*   	root:video 	0660
card.*   	root:video 	0660 =dri/
renderD128.*   	root:render 	0660 =dri/

# DVB devices
dvb([0-9])\.(.*)([0-9])* root:video	0660	>dvb/adapter%1/%2%3

# Typical devices
tty		root:root 0666
tty[0-9]*	root:root 0660
vcsa*[0-9]*	root:root 0660
ttyS[0-9]*	root:root 0660
ttyUSB[0-9]*	root:root 0660

# alsa sound devices
snd/pcm.*	root:audio 0660
snd/control.*	root:audio 0660
snd/midi.*	root:audio 0660
snd/seq		root:audio 0660
snd/timer	root:audio 0660

# input stuff
input/event[0-9]+	root:input 0640
input/mice		root:root 0640
input/mouse[0-9]	root:root 0640
input/ts[0-9]		root:root 0600

#
fb([0-9])		root:video	0660	>fb/%1

# Mass-storage devices
[hs]d[a-z][0-9]?	root:root	0664	*/etc/mdev/mdev-mount.sh

# load modules
$MODALIAS=.*	root:root 0660 @modprobe "$MODALIAS"

