# /etc/mdev.conf

# Syntax:
# [-]devicename_regex user:group mode [=path]|[>path]|[!] [@|$|*cmd args...]
# [-]$ENVVAR=regex    user:group mode [=path]|[>path]|[!] [@|$|*cmd args...]
# [-]@maj,min[-min2]  user:group mode [=path]|[>path]|[!] [@|$|*cmd args...]
#
# [-]: do not stop on this match, continue reading mdev.conf
# =: move, >: move and create a symlink
# !: do not create device node
# @|$|*: run cmd if $ACTION=remove, @cmd if $ACTION=add, *cmd in all cases

# Support module loading on hotplug
$MODALIAS=.*		root:root	0660	@modprobe "$MODALIAS"

# Normal system devices
mem	root:root	0640
kmem	root:root	0640
null	root:root	0666
zero	root:root	0666
random	root:root	0666
urandom	root:root	0666
ram	root:root	0640
ram	root:root	0640
loop	root:root	0640
rtc	root:root	0640
console	root:root	0666
tty	root:root	0666
tty	root:root	0666
ttyp	root:root	0666
ptyp	root:root	0666
ptmx	root:root	0666
ttyP	root:root	0666
ttyS	root:root	0666
fb	root:root	0640
#ttySA	root:root	0666
psaux	root:root	0666
#ppp	root:root	0666
ttyAM	root:root	0666
ttyCPM	root:root	0666
ttyAMA	root:root	0666
ttyBF	root:root	0666
ttySAC	root:root	0666
ttySC	root:root	0666
ttyPSC	root:root	0666
ttyUL	root:root	0666
ttymxc	root:root	0666
hvc	root:root	0640
# Input stuff
input		root:root	0757
input/mice	root:root	0640
input/mouse	root:root	0660
input/event	root:root	0660
#input/js	root:root	0660


# MTD stuff
mtd		root:root	0640
mtdblock	root:root	0640

#Tun/tap driver
net	root:root	0755
net/tun	root:root	0755

# Audio stuff
#audio	root:root	0666
#audio1	root:root	0666
#dsp	root:root	0666
#dsp1	root:root	0666
#sndstat	root:root	0666

# User-mode Linux stuff
#ubda	root:root	0640
#ubda	root:root	0640

# IDE Devices
hda	root:root	0640
hda	root:root	0640
hdb	root:root	0640
hdb	root:root	0640
#hdc	b	640	0	0	22	0	0	0	-
#hdc	b	640	0	0	22	1	1	1	15
#hdd	b	640	0	0	22	64	0	0	-
#hdd	b	640	0	0	22	65	1	1	15
#hde	b	640	0	0	33	0	0	0	-
#hde	b	640	0	0	33	1	1	1	15
#hdf	b	640	0	0	33	64	0	0	-
#hdf	b	640	0	0	33	65	1	1	15
#hdg	b	640	0	0	34	0	0	0	-
#hdg	b	640	0	0	34	1	1	1	15
#hdh	b	640	0	0	34	64	0	0	-
#hdh	b	640	0	0	34	65	1	1	15

# SCSI Devices
sda	b	640	0	0	8	0	0	0	-
sda	b	640	0	0	8	1	1	1	15
sdb	b	640	0	0	8	16	0	0	-
sdb	b	640	0	0	8	17	1	1	15
#sdc	b	640	0	0	8	32	0	0	-
#sdc	b	640	0	0	8	33	1	1	15
#sdd	b	640	0	0	8	48	0	0	-
#sdd	b	640	0	0	8	49	1	1	15
#sde	b	640	0	0	8	64	0	0	-
#sde	b	640	0	0	8	65	1	1	15
#sdf	b	640	0	0	8	80	0	0	-
#sdf	b	640	0	0	8	81	1	1	15
#sdg	b	640	0	0	8	96	0	0	-
#sdg	b	640	0	0	8	97	1	1	15
#sdh	b	640	0	0	8	112	0	0	-
#sdh	b	640	0	0	8	113	1	1	15
#sg	c	640	0	0	21	0	0	1	15
#scd	b	640	0	0	11	0	0	1	15
#st	c	640	0	0	9	0	0	1	8
#nst	c	640	0	0	9	128	0	1	8
#st	c	640	0	0	9	32	1	1	4
#st	c	640	0	0	9	64	1	1	4
#st	c	640	0	0	9	96	1	1	4

# USB block devices (ub driver)
uba	root:root	0640
uba	root:root	0640
ubb	root:root	0640
ubb	root:root	0640

# Floppy disk devices
#fd	b	640	0	0	2	0	0	1	2
#fd0d360	b	640	0	0	2	4	0	0	-
#fd1d360	b	640	0	0	2	5	0	0	-
#fd0h1200	b	640	0	0	2	8	0	0	-
#fd1h1200	b	640	0	0	2	9	0	0	-
#fd0u1440	b	640	0	0	2	28	0	0	-
#fd1u1440	b	640	0	0	2	29	0	0	-
#fd0u2880	b	640	0	0	2	32	0	0	-
#fd1u2880	b	640	0	0	2	33	0	0	-

# I2C device nodes
i2c-	root:root	0666

# v4l device nodes
video	root:root	0666
